name: Docker Image CI

on: push
# on: 
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

env:
  # Enable BuildKit
  DOCKER_BUILDKIT: 1
  IMAGE_NAME: console-application
  IMAGE_TAG: 0.1

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Login GitHub Registry
      run: docker login docker.pkg.github.com -u owner -p ${{ secrets.GITHUB_TOKEN }}
      
    - name: Build the Docker image
      run: docker build -t docker.pkg.github.com/${{ github.repository }}/${IMAGE_NAME}:${IMAGE_TAG} --file Dockerfile .

    - name: Push image to GitHub Registry
      run: docker push docker.pkg.github.com/${{ github.repository }}/${IMAGE_NAME}:${IMAGE_TAG}

    - name: Hello world action
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

    - name: Notify Result to Slack
      uses: rtCamp/action-slack-notify@v2.0.0
      if: always()
      with:
        SLACK_CHANNEL: dotnet-sample-application
        SLACK_COLOR: '#3278BD'
        SLACK_MESSAGE: ${{ job.status }}
        SLACK_TITLE: ${{ github.ref }}
        SLACK_USERNAME: Github Actions
        SLACK_WEBHOOK: ${SLACK_WEBHOOK}
